### ISSUE TITLE
Incorrectly passing expiry time to JWT

### ISSUE THREAD

**Issue by heysailor** [prescottprue/machinepack-jwt#1]
Looking through the source code, I think it's making non-expiring JWT tokens. If you specify an expiry time to the machinepack, no exp is set in the payload.

The underlying jsonwebtoken package needs the expiry time set as options.expiresInSeconds or options.expiresInMinutes.

To fix, change the machine pack inputs from options.expires to either of the above.

**Comment by prescottprue** [comment]
Fixed by merging [your pull request](https://github.com/prescottprue/machinepack-jwt/pull/2). Apologies for taking a while. Thanks
